### ISSUE TITLE
InBrowserFullscreen:false for safari iOS 13 does not show full Native Player UI

### ISSUE THREAD

**Issue by dseeker** [kaltura/playkit-js#477]
##### Prerequisites

- [x] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-js/issues): **\_\_**
- [x] Which Player [version](https://github.com/kaltura/playkit-js/releases) are you using: **latest on SaaS cloud platform**
- [x] Can you reproduce the issue with our latest release version: Kaltura Player lib
* kaltura-ovp-player v0.55.0
* playkit-cast-sender v0.4.2
* playkit-flash v1.4.4
* playkit-ima v0.20.4
* playkit-offline-manager v1.2.0
- [x] Can you reproduce the issue with the latest code from master: **yes**
- [x] What browser and OS names and versions are you using: **ios, iPad, safari, latest**
- [ ] If applicable, add test code or test page to reproduce:

```

playback: {
						preload: 'auto',
						autoplay: true,
						loop: false,
						allowMutedAutoPlay: true,
						playsinline: false,
						inBrowserFullscreen: false,

```

##### Expected behavior

With inBrowserFullscreen set to false, Touching the fullscreen button should bring the native player UI.

##### Actual behavior

instead, the fullscreen works but the web UI remains on the bottom part with the player. This web ui does not include the airplay button. It works correctly for Chrome and Firefox on iOS, only Safari does not.

##### Console output

```
Paste the contents of the browser console here.
```

```
For media errors reported on Chrome browser, please also paste the output of chrome://media-internals
```

**Comment by OrenMe** [comment]
Apple has fullscreen api on IpadOS(ios13 on iPad) enabled by default without an option to turn it off.
This is available in safari only and not in other browsers on iPad.
The config option you mentioned is applicable on iPhone iOS and iPad before ios13.
See https://caniuse.com/#feat=fullscreen

**Comment by dseeker** [comment]
Maybe I was not able to explain properly, I’ll try to illustrate.
If you visit this page with the earlier Kaltura player on iPad ios13 on Safari and press fullscreen it will show the native player UI with airplay control.
![8E73F3BA-C7DB-4679-858D-6F35E3FEA0C1](https://user-images.githubusercontent.com/11655138/89729853-d03ef780-da39-11ea-86ac-aafc37c366c8.png)

But when I’m using the V7 player when I press fullscreen it shows the left top close and PIP native player UI but keeps the web UI hiding the airplay control.
![0A84755B-A55A-4B64-8665-8E0E502DB8D9](https://user-images.githubusercontent.com/11655138/89729881-1ac07400-da3a-11ea-8f33-88cf63814df5.png)

I would really like not to have some jenky conditional to detect the user’s os and browser and having to pass a different Kaltura player library version just to get the same functionality that appears for Chome and Safari. It doesn’t seem like it’s a OS limitation if the previous version of player can still behave as expected.

Please review and test this problem before dismissing it

**Comment by OrenMe** [comment]
Hi @dseeker, previous player is using legacy methods to detect platform support and also is bounded to old/previous behaviour.
There is also an option to set this in mwEmbed but it will break the existing functionality it has.
playkit is a modern player and uses platform/environment native APIs to detect feature support.
In this case it always favours modern apis over legacy.
Apple added support for standard native fullscreen API in iOS12 behind a flag and now they have removed this flag so the feature detection takes precedence.
We do not intend to fallback to previous native UI as this gives lesser control to users, like seekbar preview for example or playback rate selection.
If you are a platform partner please reach out through your account manager and raise this a request so we may consider this.
If I try to read between the lines I think what you are aiming for is the airplay support - is this correct?
If this is correct please also raise this as a request so may be able to consider adding this if supported by API.

**Comment by dseeker** [comment]
I understand the trade offs and have sent this link to our account manager.

Regarding the seekbar preview, there seems to actually be a problem seeking in iOS device, neither in chrome or safari, when you drag the playkit player seekbar it does not updates the image or shows any preview, only when you release your finger it updates. This behavior in the Native Player UI actually does changes the video image WHILE you drag with your finger, without having to release. So there seems to be some problem there as well.

If there is no solution, In the end we'll have to either explain to our users they cannot Airplay from a Safari browser in IOS, they must install Chrome or Firefox to get to do so which seems like a very big ask. In the meanwhile I guess we'll have to present the user with the "older" but functional version for the player for Safari users is they need to use Airplay.

Thanks

**Comment by OrenMe** [comment]
thanks @dseeker, this is valuable feedback.
I think also having to go to fullscreen in order to get airplay might be considered a lesser UX.
I'll also share this input with product and have opened an internal ticket to address AirPlay support.
You can pass this to your account manager for reference: FEC-10405.

If you can share your partner ID I'll link the ticket as well.
