### ISSUE TITLE
TypeError: this._logger.enabledFor is not a function | Category:7 | Code:7010 

### ISSUE THREAD

**Issue by dseeker** [kaltura/playkit-js#494]
##### Prerequisites

- [x] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-js/issues): **\_\_**
- [x] Which Player [version](https://github.com/kaltura/playkit-js/releases) are you using: **1.0.3**
- [x] Can you reproduce the issue with our latest release version: **\_\_**
- [ ] Can you reproduce the issue with the latest code from master: **\_\_**
- [x] What browser and OS names and versions are you using: **Windows Chrome latest**
- [ ] If applicable, add test code or test page to reproduce:

```

```

##### Expected behavior

load "playkit-js-hotspots" plugin

##### Actual behavior

error in console, hotspots no longer display in entry

##### Console output

```
dcbf1ef6da883ba8205d.js:2 [Error] Category:7 | Code:7010 | TypeError: this._logger.enabledFor is not a function
    at e._log (contrib-logger.ts:62)
    at e.error (contrib-logger.ts:113)
    at Function.t.createPlugin (core-plugin-proxy.ts:61)
    at e.t.load (plugin-manager.js:100)
    at kaltura-player.js:667
    at Array.forEach (<anonymous>)
    at Proxy.s._configureOrLoadPlugins (kaltura-player.js:657)
    at Proxy.s.configure (kaltura-player.js:194)
    at Proxy.s.setMedia (kaltura-player.js:105)
    at kaltura-player.js:79

```

code
```
private _log(
    loggerMethod: LoggerMethods,
    level: LogLevel,
    message: string,
    messageContext: MessageOptions
  ): void {
    if (!this._logger.enabledFor(level)) {
      return;
    }

```

```
For media errors reported on Chrome browser, please also paste the output of chrome://media-internals
```

**Comment by OrenMe** [comment]
This error is coming from the playkit-js-hotspots.
Please open an issue there.
